name: Sinhala workflow
on:
  schedule: # Run workflow automatically
    - cron: '*/5 * * * *' # Runs every 5 minitues
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with Sinhala Quote
    runs-on: ubuntu-latest
    steps:
      - name: Sinhala Quote Of The Day
        uses: dinushchathurya/sinhala-quotes-github-action@1.0.1

